name: city_sphere
description: "A global feel to city data exploration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

 # State management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  # Networking
  dio: ^5.8.0+1

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # JSON serialization
  json_annotation: ^4.9.0

  # UI Essentials
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/